# Generated by Django 5.0.2 on 2024-04-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='products1',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
