# Generated by Django 5.0.2 on 2024-04-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='buyer',
            field=models.CharField(max_length=100),
        ),
    ]
