# Generated by Django 5.0.2 on 2024-04-25 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='last_name',
        ),
    ]
