# Generated by Django 5.0.2 on 2024-04-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_review_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
